<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Ppantelakis\BarCode\Service\BarCodeServiceInterface'             => __DIR__ . '/src/Service/BarCodeServiceInterface.php',
  'Ppantelakis\BarCode\Service\BarCodeServiceAwareTrait'            => __DIR__ . '/src/Service/BarCodeServiceAwareTrait.php',
  'Ppantelakis\BarCode\Service\BarCodeService'                      => __DIR__ . '/src/Service/BarCodeService.php',
  'Ppantelakis\BarCode\Service\BarCodeServiceAwareInterface'        => __DIR__ . '/src/Service/BarCodeServiceAwareInterface.php',
  'Ppantelakis\BarCode\View\Helper\Factory\BarCodeHelperFactory'    => __DIR__ . '/src/View/Helper/Factory/BarCodeHelperFactory.php',
  'Ppantelakis\BarCode\View\Helper\BarCodeHelper'                   => __DIR__ . '/src/View/Helper/BarCodeHelper.php',
  'Ppantelakis\BarCode\View\Helper\BarCodeHelperInterface'          => __DIR__ . '/src/View/Helper/BarCodeHelperInterface.php',
  'Ppantelakis\BarCode\Module'                                     => __DIR__ . '/src/Module.php',
  'Ppantelakis\BarCode\Controller\Factory\BarCodeControllerFactory' => __DIR__ . '/src/Controller/Factory/BarCodeControllerFactory.php',
  'Ppantelakis\BarCode\Controller\BarCodeController'                => __DIR__ . '/src/Controller/BarCodeController.php',
  'Ppantelakis\BarCode\Exception\InvalidImagetypeException'        => __DIR__ . '/src/Exception/InvalidImagetypeException.php',
);
